#!/usr/bin/env python

import getopt, sys
import argparse
import json

CONFIG_FILE = u"../lokalise_config.json"

with open(CONFIG_FILE) as f:
    data = json.load(f)
    PLATFORM_TYPE = data['platform']
    LOCALIZATION_FOLDER = data['localization_path']
    LOCALIZATION_SETTINGS_FOLDER = data['localization_settings_path']
    PROJECT_NAME = data['project_name']
    LOKALISE_TOKEN = data['lokalise_token']
    LOKALISE_PROJECT_ID = data['lokalise_project_id']
    SETTINGS_PLIST_KEYS = data['setting_plist_keys']
    IGNORE_PROJECT_TAG = data['ignore_project_tag']

print('Starting importing localization for lokalise...')

parser = argparse.ArgumentParser(description='Use --full for importing all languages.\n Use --tags [tag1, tag2, ...] for importing with tags')
parser.add_argument('--full', nargs='?', const=1, type=int, default=0)
parser.add_argument('--tags', nargs='+', default=None)
parser.add_argument('--clean_file', nargs='?', default=None)
args = parser.parse_args()

full_import = args.full
clean_file = args.clean_file

tags = args.tags
if not IGNORE_PROJECT_TAG:
    tags = ([PROJECT_NAME] + tags) if tags != None else [PROJECT_NAME]

if PLATFORM_TYPE == "ios":
    import lokalise_ios
    lokalise_ios.localization_import(LOCALIZATION_FOLDER, LOCALIZATION_SETTINGS_FOLDER, SETTINGS_PLIST_KEYS, LOKALISE_TOKEN, LOKALISE_PROJECT_ID, full_import, tags)
else:
    import lokalise_android
    lokalise_android.localization_import(LOCALIZATION_FOLDER, LOKALISE_TOKEN, LOKALISE_PROJECT_ID, full_import, tags, clean_file)

print('Finished importing localization to lokalise...')
